# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOwPJzrqFJod_UgrnuvvfnEJoaRo151K
"""

numpy
scipy
cvxpy
matplotlib
pyyaml
tqdm

